[package]
name = "didresolver"
version = "0.0.4"
edition = "2021"
description = "DID resolver for different did methods"
authors = ["Jonas Niestroj", "Frithjof Hoppe", "Vladica Stojic"]
homepage = "https://github.com/e-id-admin"
readme = "README.md"
include = [
    "Cargo.toml",
    "README.md",
    "src/**/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.213", features = ["derive"] }
serde_json = "1.0.132"
thiserror = "1.0.65"
openssl = { version = "0.10.68", features = ["vendored"] }
uniffi = { version = "0.28.2", features = ["cli"] }
ssi = { version = "0.9.0", features = ["example", "http-did"] }
strum = { version = "0.26", features = ["derive"] }
minify = "1.3"
didtoolbox = { git = "https://github.com/e-id-admin/didtoolbox.git", tag = "0.0.3" }
# When building on a container (podman run -it --rm -v $(pwd):$(pwd):Z -v $HOME/.ssh:/root/.ssh:Z -w $(pwd) rust), the local repo may be used:
#didtoolbox = { path = "../didtoolbox" }

[build-dependencies]
uniffi = { version = "0.28.2", features = ["build"] }

[dev-dependencies]
rstest = "0.23.0"
mockito = "1.5.0"
ureq = "2.10.1"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "didresolver"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
