[package]
name = "didresolver"
version = "0.0.3"
edition = "2021"
description = "DID resolver for different did methods"
authors = ["Jonas Niestroj", "Frithjof Hoppe"]
homepage = "https://github.com/e-id-admin"
readme = "README.md"
include = [
    "Cargo.toml",
    "README.md",
    "src/**/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.8", features = ["blocking"] }
serde = { version = "1.0.210", features = ["derive"] }
serde_json = "1.0.128"
thiserror = "1.0.58"
openssl = { version = "0.10.68", features = ["vendored"] }
uniffi = { version = "0.28.2", features = ["cli"] }
# TODO Set the tag properly for didtoolbox - it should be probably 0.0.3 (after merging of https://github.com/e-id-admin/didtoolbox/pull/2)
didtoolbox = { git = "https://github.com/e-id-admin/didtoolbox.git", branch = "feat/EIDSYS-262" }
#didtoolbox = { path = "../didtoolbox" }

[build-dependencies]
uniffi = { version = "0.28.2", features = ["build"] }

[dev-dependencies]
rstest = "0.23.0"
minify = "1.3"

[lib]
crate-type = ["lib", "cdylib", "staticlib"]
name = "didresolver"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"
