[package]
name = "didresolver"
version = "0.1.0"
edition = "2021"
description = "DID resolver for different did methods"
authors = ["Jonas Niestroj", "Frithjof Hoppe"]
homepage = "https://github.com/e-id-admin"
readme = "README.md"
include = [
    "Cargo.toml",
    "README.md",
    "src/**/*",
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.2", features = ["blocking"] }
serde = {version = "1.0.202", features = ["derive"]}
serde_json = "1.0.115"
thiserror = "1.0.58"
openssl = { version = "0.10.35", features = ["vendored"] }
uniffi = { version = "0.26.1", features = ["cli"] }
didtoolbox = {git = "https://github.com/e-id-admin/didtoolbox.git", branch = "build/rust"}
 
[build-dependencies]
uniffi = { version = "0.26.1", features = ["build"] }

[lib]
crate-type = ["cdylib"]
name = "didresolver"

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"