[package]
name = "didresolver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = { version = "0.12.2", features = ["blocking"] }
serde = "1.0.197"
serde_derive = "1.0.197"
serde_json = "1.0.115"
thiserror = "1.0.58"
openssl = { version = "0.10.35", features = ["vendored"] }
uniffi = { version = "0.26.1", features = ["cli"] }

[build-dependencies]
uniffi = { version = "0.26.1", features = ["build"] }

[lib]
crate-type = ["staticlib", "cdylib"]

[[bin]]
name = "uniffi-bindgen"
path = "uniffi-bindgen.rs"